### ISSUE TITLE
list index out of range for pypi/rst2pdf/0.93

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-worker#117]
```python
{"node_args": {"recursive_limit": 0, "ecosystem": "pypi", "version": "0.93", "name": "rst2pdf", "force_graph_sync": false, "force": true}, "task_name": "InitAnalysisFlow", "record_id": null, "error_traceback": "  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 114, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py\", line 47, in execute\n    target_dir=cache_path\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/process.py\", line 271, in fetch_artifact\n    file_url = release_files[0]['url']\n", "storage_task_name": "InitAnalysisFlow", "flow_name": "bayesianFlow", "error_type": "<class 'IndexError'>", "event": "STORAGE_STORE_ERROR", "error_value": "list index out of range", "storage_name": "BayesianPostgres", "task_id": "0e72f7e2-9554-4c81-b7fe-1fec53aca450"}
2017-07-17 08:43:37,111 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[0e72f7e2-9554-4c81-b7fe-1fec53aca450] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 169, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 114, in run
    result = task.run(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run
    result = self.execute(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py", line 47, in execute
    target_dir=cache_path
  File "/usr/lib/python3.4/site-packages/f8a_worker/process.py", line 271, in fetch_artifact
    file_url = release_files[0]['url']
IndexError: list index out of range
```

**Comment by jpopelka** [comment]
https://pypi.python.org/pypi/rst2pdf/json contains:

```json
"0.93": [ ],
"0.92": [

    {
        "has_sig": false,
        "upload_time": "2012-12-19T12:29:56",
        "comment_text": "",
        "python_version": "source",
        "url": "https://pypi.python.org/packages/7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz",
        "md5_digest": "25a7cb339869946e52dc750c4f4b6536",
        "downloads": 400285,
        "filename": "rst2pdf-0.93.tar.gz",
        "packagetype": "sdist",
        "path": "7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz",
        "size": 1301775
    }
]
```
