### ISSUE TITLE
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-worker#191]
Trying to scan `nuget:Json.NET:10.0.3`:

```

2017-08-02 20:49:56,485 [INFO] celery.worker.strategy: Received task: selinon.Dispatcher[438ac9ef-50a5-418b-9f1a-77db1e1ed5d5]
--
  | {"event": "DISPATCHER_WAKEUP", "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}, "queue": "STAGE_ingestion_bayesianFlow_v0", "selective": false, "dispatcher_id": "438ac9ef-50a5-418b-9f1a-77db1e1ed5d5", "flow_name": "bayesianFlow", "state": null, "retry": null}
  | {"event": "FLOW_START", "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}, "selective": false, "dispatcher_id": "438ac9ef-50a5-418b-9f1a-77db1e1ed5d5", "flow_name": "bayesianFlow", "queue": "STAGE_ingestion_bayesianFlow_v0"}
  | {"foreach_str": null, "selective_edge": false, "parent": {}, "countdown": null, "event": "TASK_SCHEDULE", "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}, "task_id": "e96efc79-db25-44ea-b5ae-36ea8045e938", "selective": false, "task_name": "InitAnalysisFlow", "flow_name": "bayesianFlow", "dispatcher_id": "438ac9ef-50a5-418b-9f1a-77db1e1ed5d5", "queue": "STAGE_ingestion_InitAnalysisFlow_v0", "condition_str": "True"}
  | {"event": "DISPATCHER_RETRY", "retry": 10, "queue": "STAGE_ingestion_bayesianFlow_v0", "selective": false, "dispatcher_id": "438ac9ef-50a5-418b-9f1a-77db1e1ed5d5", "state_dict": {"active_nodes": [{"name": "InitAnalysisFlow", "id": "e96efc79-db25-44ea-b5ae-36ea8045e938"}], "finished_nodes": {}, "waiting_edges": [1, 2, 3], "failed_nodes": {}}, "flow_name": "bayesianFlow", "parent": null, "state": {"active_nodes": [{"name": "InitAnalysisFlow", "id": "e96efc79-db25-44ea-b5ae-36ea8045e938"}], "finished_nodes": {}, "waiting_edges": [1, 2, 3], "failed_nodes": {}}, "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}}
  | 2017-08-02 20:49:56,845 [INFO] celery.app.trace: Task selinon.Dispatcher[438ac9ef-50a5-418b-9f1a-77db1e1ed5d5] retry: Retry in 10s
  | 2017-08-02 20:49:56,905 [INFO] celery.worker.strategy: Received task: selinon.SelinonTaskEnvelope[e96efc79-db25-44ea-b5ae-36ea8045e938]
  | {"event": "TASK_START", "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}, "task_id": "e96efc79-db25-44ea-b5ae-36ea8045e938", "task_name": "InitAnalysisFlow", "flow_name": "bayesianFlow", "dispatcher_id": "438ac9ef-50a5-418b-9f1a-77db1e1ed5d5", "queue": "STAGE_ingestion_InitAnalysisFlow_v0", "parent": {}}
  | {"storage_name": "BayesianPostgres", "event": "STORAGE_CONNECT"}
  | {"what": "Traceback (most recent call last):\n  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py\", line 22, in execute\n    e = Ecosystem.by_name(db, arguments['ecosystem'])\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/models.py\", line 92, in by_name\n    return cls._by_attrs(session, name=name)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/models.py\", line 45, in _by_attrs\n    return session.query(cls).filter_by(**attrs).one()\n  File \"/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py\", line 2820, in one\n    raise orm_exc.NoResultFound(\"No row was found for one()\")\nsqlalchemy.orm.exc.NoResultFound: No row was found for one()\n", "parent": {}, "event": "TASK_FAILURE", "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}, "task_id": "e96efc79-db25-44ea-b5ae-36ea8045e938", "dispatcher_id": "438ac9ef-50a5-418b-9f1a-77db1e1ed5d5", "flow_name": "bayesianFlow", "task_name": "InitAnalysisFlow", "queue": "STAGE_ingestion_InitAnalysisFlow_v0", "retried_count": 0}
  | {"storage_task_name": "InitAnalysisFlow", "error_value": "No row was found for one()", "record_id": null, "event": "STORAGE_STORE_ERROR", "storage_name": "BayesianPostgres", "node_args": {"version": "10.0.3", "force": true, "name": "Json.NET", "recursive_limit": 0, "ecosystem": "nuget", "force_graph_sync": false}, "error_traceback": "  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py\", line 22, in execute\n    e = Ecosystem.by_name(db, arguments['ecosystem'])\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/models.py\", line 92, in by_name\n    return cls._by_attrs(session, name=name)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/models.py\", line 45, in _by_attrs\n    return session.query(cls).filter_by(**attrs).one()\n  File \"/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py\", line 2820, in one\n    raise orm_exc.NoResultFound(\"No row was found for one()\")\n", "task_id": "e96efc79-db25-44ea-b5ae-36ea8045e938", "task_name": "InitAnalysisFlow", "flow_name": "bayesianFlow", "error_type": "<class 'sqlalchemy.orm.exc.NoResultFound'>"}
  | 2017-08-02 20:49:57,102 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[e96efc79-db25-44ea-b5ae-36ea8045e938] raised unexpected: NoResultFound('No row was found for one()',)
  | Traceback (most recent call last):
  | File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
  | return self.run(*args, **kwargs)
  | File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
  | raise self.retry(max_retries=0, exc=exc)
  | File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
  | raise_with_context(exc)
  | File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
  | result = task.run(node_args)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run
  | result = self.execute(node_args)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py", line 22, in execute
  | e = Ecosystem.by_name(db, arguments['ecosystem'])
  | File "/usr/lib/python3.4/site-packages/f8a_worker/models.py", line 92, in by_name
  | return cls._by_attrs(session, name=name)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/models.py", line 45, in _by_attrs
  | return session.query(cls).filter_by(**attrs).one()
  | File "/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2820, in one
  | raise orm_exc.NoResultFound("No row was found for one()")
  | sqlalchemy.orm.exc.NoResultFound: No row was found for one()


```

**Comment by msrb** [comment]
Looks like a bug in alembic migrations. Existing deployments won't recognize nuget ecosystem.

**Comment by jpopelka** [comment]
> Trying to scan nuget:Json.NET:10.0.3

The package is actually called [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json).
`Json.NET` is a `title`, which according to [spec](https://docs.microsoft.com/en-us/nuget/schema/nuspec) means: *"A human-friendly title of the package, typically used in UI displays as on nuget.org and the Package Manager in Visual Studio."*

**Comment by msrb** [comment]
Yeah, but I think that's actually irrelevant. The error seems to be caused by unknown 'nuget' ecosystem, which suggests that changes in alembic did not insert the new ecosystem into the DB.

**Comment by jpopelka** [comment]
I know, if I was thinking it's the cause I'd have closed the issue :-)

**Comment by fridex** [comment]
> The error seems to be caused by unknown 'nuget' ecosystem, which suggests that changes in alembic did not insert the new ecosystem into the DB.

+1, here is ecosystem list from prod:

```json
{
  "matched": [
    {
      "_backend": "rubygems",
      "fetch_url": "https://rubygems.org/api/v1",
      "id": 1,
      "name": "rubygems",
      "url": "https://rubygems.org/"
    },
    {
      "_backend": "npm",
      "fetch_url": "https://registry.npmjs.org/",
      "id": 2,
      "name": "npm",
      "url": "https://www.npmjs.com/"
    },
    {
      "_backend": "maven",
      "fetch_url": null,
      "id": 3,
      "name": "maven",
      "url": "https://repo1.maven.org/maven2/"
    },
    {
      "_backend": "pypi",
      "fetch_url": "https://pypi.python.org/pypi",
      "id": 4,
      "name": "pypi",
      "url": "https://pypi.python.org/"
    },
    {
      "_backend": "scm",
      "fetch_url": null,
      "id": 5,
      "name": "go",
      "url": null
    },
    {
      "_backend": "crates",
      "fetch_url": null,
      "id": 6,
      "name": "crates",
      "url": "https://crates.io/"
    }
  ]
}
```

**Comment by fridex** [comment]
> +1, here is ecosystem list from prod:

BTW staging is same...

**Comment by msrb** [comment]
The problem probably is that we don't have alembic migration for adding the new ecosystem.

**Comment by msrb** [comment]
So all deployments, except greenfield ones, are affected.

**Comment by jpopelka** [comment]
The alembic migration should be [here](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/alembic/versions/a31c98c74ea0_add_e_p_v.py#L37)

**Comment by msrb** [comment]
> The alembic migration should be here

That won't be executed if the DB is already running newer DB schema, i.e. modifying older migration scripts won't affect existing deployments. I think we need to create a new migration with just that one 'nuget' insert.
