### ISSUE TITLE
psycopg2.InternalError: ALTER TYPE ... ADD cannot run inside a transaction block

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-worker#219]
I can see following error on staging:

```
[fabric8-analytics-worker-master] Running shell script
+ oc logs -f dc/bayesian-worker-api
--> pre: Running hook pod ...
+ RESULT=1
+ ((  1 != 0  ))
+ echo 'Trying to create database...'
Trying to create database...
+ psql -h bayesian-pgbouncer -p 5432 -U coreapi -d postgres -tc 'SELECT 1 FROM pg_database WHERE datname = '\''coreapi'\'''
+ grep -q 1
+ RESULT=0
+ ((  0 == 0  ))
+ echo 'Database created'
+ ((  0 != 0  ))
+ pushd /alembic
+ export MIGRATE_ONLY=1
+ MIGRATE_ONLY=1
+ alembic upgrade head
Database created
/alembic ~
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade e2762a61d34c -> f8bb0efac483, nuget ecosystem
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.InternalError: ALTER TYPE ... ADD cannot run inside a transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python3.4/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python3.4/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python3.4/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/lib/python3.4/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.4/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "alembic/env.py", line 84, in <module>
    run_migrations_online()
  File "alembic/env.py", line 79, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python3.4/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python3.4/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/alembic/alembic/versions/f8bb0efac483_nuget_ecosystem.py", line 23, in upgrade
    conn.execute("ALTER TYPE ecosystem_backend_enum ADD VALUE 'nuget'")
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.InternalError) ALTER TYPE ... ADD cannot run inside a transaction block
 [SQL: "ALTER TYPE ecosystem_backend_enum ADD VALUE 'nuget'"]
```

**Comment by msrb** [comment]
Fixed 😉 Thanks.
