### ISSUE TITLE
An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-worker#231]
I know this is not a bug, but since we know what is going on there (new package, or attempt to analyze non-existent package), we should just log what happened, but don't dump the whole stacktrace.

I hope we will have some stacktrace/log monitoring in place, and these would be always false alarms.

```
{"event": "STORAGE_CONNECT", "storage_name": "S3Artifacts"}
--
  | 2017-08-10 08:42:54,066 [ERROR] f8a_worker.object_cache: Failed to retrieve nuget/NUnit/3.6.1/meta.json
  | Traceback (most recent call last):
  | File "/usr/lib/python3.4/site-packages/f8a_worker/object_cache.py", line 69, in _get_meta
  | self._meta = self._s3.retrieve_dict(self._meta_json_object_key)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/storages/s3.py", line 195, in retrieve_dict
  | return json.loads(self.retrieve_blob(object_key).decode())
  | File "/usr/lib/python3.4/site-packages/f8a_worker/storages/s3.py", line 191, in retrieve_blob
  | return self._s3.Object(self.bucket_name, object_key).get()['Body'].read()
  | File "/usr/lib/python3.4/site-packages/boto3/resources/factory.py", line 520, in do_action
  | response = action(self, *args, **kwargs)
  | File "/usr/lib/python3.4/site-packages/boto3/resources/action.py", line 83, in __call__
  | response = getattr(parent.meta.client, operation_name)(**params)
  | File "/usr/lib/python3.4/site-packages/botocore/client.py", line 310, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/usr/lib/python3.4/site-packages/botocore/client.py", line 599, in _make_api_call
  | raise error_class(parsed_response, operation_name)
  | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.


```

**Comment by jpopelka** [comment]
> we should just log what happened, but don't dump the whole stacktrace

Hmm, we already [wrap the retrieve_dict() call with try - except](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/object_cache.py#L69), no idea why the exception is not caught.
