### ISSUE TITLE
Unable to create new bucket in production for gathering package descriptions

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-worker#320]
```
2017-09-11 20:22:04,264 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[bc8e1f0c-a3ba-4f77-8e58-cf07c48efa85] raised unexpected: ClientError('An error occurred (TooManyBuckets) when calling the CreateBucket operation: You have attempted to create more buckets than allowed',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 120, in run
    StoragePool.set(node_args, flow_name, task_name, self.request.id, result)
  File "/usr/lib/python3.4/site-packages/selinon/storagePool.py", line 137, in set
    record_id = storage.store(node_args, flow_name, storage_task_name, task_id, result)
  File "/usr/lib/python3.4/site-packages/f8a_worker/storages/s3_description_repository.py", line 20, in store
    self.store_blob(result.encode(), object_key)
  File "/usr/lib/python3.4/site-packages/f8a_worker/storages/s3.py", line 163, in store_blob
    self._create_bucket_if_needed()
  File "/usr/lib/python3.4/site-packages/f8a_worker/storages/s3.py", line 76, in _create_bucket_if_needed
    self._create_bucket()
  File "/usr/lib/python3.4/site-packages/f8a_worker/storages/s3.py", line 84, in _create_bucket
    self._s3.create_bucket(Bucket=self.bucket_name)
  File "/usr/lib/python3.4/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python3.4/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.4/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (TooManyBuckets) when calling the CreateBucket operation: You have attempted to create more buckets than allowed
```

**Comment by fridex** [comment]
Closing this, clean up helped.
