### ISSUE TITLE
No release files for version 3.10.0beta0 (pwnable)

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-worker#322]
```
{"dispatcher_id": "977528ce-4b69-4d74-bb78-1cadf1b633f4", "task_id": "3f88d6c5-ea54-4e38-9ba0-0ad5afd47800", "event": "TASK_FAILURE", "parent": {}, "node_args": {"version": "3.10.0beta0", "ecosystem": "pypi", "name": "pwnable"}, "flow_name": "bayesianFlow", "queue": "prod_ingestion_InitAnalysisFlow_v0", "what": "Traceback (most recent call last):\n  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py\", line 47, in execute\n    target_dir=cache_path\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/process.py\", line 275, in fetch_artifact\n    raise RuntimeError(\"No release files for version %s\" % version)\nRuntimeError: No release files for version 3.10.0beta0\n", "task_name": "InitAnalysisFlow", "retried_count": 0}
{"node_args": {"version": "3.10.0beta0", "ecosystem": "pypi", "name": "pwnable"}, "error_value": "No release files for version 3.10.0beta0", "event": "STORAGE_OMIT_STORE_ERROR", "error_type": "<class 'RuntimeError'>", "error_traceback": "  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py\", line 47, in execute\n    target_dir=cache_path\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/process.py\", line 275, in fetch_artifact\n    raise RuntimeError(\"No release files for version %s\" % version)\n", "task_id": "3f88d6c5-ea54-4e38-9ba0-0ad5afd47800", "flow_name": "bayesianFlow", "task_name": "InitAnalysisFlow"}
2017-09-11 20:47:07,420 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[3f88d6c5-ea54-4e38-9ba0-0ad5afd47800] raised unexpected: RuntimeError('No release files for version 3.10.0beta0',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
    result = task.run(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run
    result = self.execute(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/init_analysis_flow.py", line 47, in execute
    target_dir=cache_path
  File "/usr/lib/python3.4/site-packages/f8a_worker/process.py", line 275, in fetch_artifact
    raise RuntimeError("No release files for version %s" % version)
RuntimeError: No release files for version 3.10.0beta0
```

**Comment by fridex** [comment]
I saw this multiple times in logs (for python ecosystem).

@pkajaba could you ensure these analyses analyses are scheduled from firehose-fetcher correctly? Thanks!

**Comment by jpopelka** [comment]
It's a problem on libraries.io side:

They claim the latest version of pwnable is 3.10.0beta0, while pypi says it's 1.0.
https://libraries.io/pypi/pwnable
https://pypi.python.org/pypi/pwnable/

They are probably confused by pwntools, whose latest version is 3.10.0b0
https://pypi.python.org/pypi/pwntools/3.10.0b0
https://libraries.io/pypi/pwntools

**Comment by pkajaba** [comment]
@jpopelka nice catch. You seem to be right, but I am afraid there is nothing we can do.
