### ISSUE TITLE
ValueError: invalid interpolation syntax in 'postgresql://coreapi:***@bayesian-pgbouncer:5432

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-worker#386]
Failure from prod, seems to be caused by RDS password containing `%` sign. 

```
Readiness probe failed: + pushd /alembic ++ grep '(head)' /alembic ~ ++ awk '{ print $1 }' ++ alembic heads + wanted=f8bb0efac483 ++ alembic current ++ grep '(head)' ++ awk '{ print $1 }' Traceback (most recent call last): File "/usr/bin/alembic", line 11, in <module> sys.exit(main()) File "/usr/lib/python3.4/site-packages/alembic/config.py", line 479, in main CommandLine(prog=prog).main(argv=argv) File "/usr/lib/python3.4/site-packages/alembic/config.py", line 473, in main self.run_cmd(cfg, options) File "/usr/lib/python3.4/site-packages/alembic/config.py", line 456, in run_cmd **dict((k, getattr(options, k, None)) for k in kwarg) File "/usr/lib/python3.4/site-packages/alembic/command.py", line 457, in current script.run_env() File "/usr/lib/python3.4/site-packages/alembic/script/base.py", line 425, in run_env util.load_python_file(self.dir, 'env.py') File "/usr/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file module = load_module_py(module_id, path) File "/usr/lib/python3.4/site-packages/alembic/util/compat.py", line 64, in load_module_py module_id, path).load_module(module_id) File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper File "<frozen importlib._bootstrap>", line 1614, in load_module File "<frozen importlib._bootstrap>", line 596, in _load_module_shim File "<frozen importlib._bootstrap>", line 1220, in load File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked File "<frozen importlib._bootstrap>", line 1129, in _exec File "<frozen importlib._bootstrap>", line 1471, in exec_module File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed File "alembic/env.py", line 16, in <module> config.set_main_option('sqlalchemy.url', os.environ['F8A_POSTGRES']) File "/usr/lib/python3.4/site-packages/alembic/config.py", line 218, in set_main_option self.set_section_option(self.config_ini_section, name, value) File "/usr/lib/python3.4/site-packages/alembic/config.py", line 245, in set_section_option self.file_config.set(section, name, value) File "/usr/lib64/python3.4/configparser.py", line 1166, in set super().set(section, option, value) File "/usr/lib64/python3.4/configparser.py", line 871, in set value) File "/usr/lib64/python3.4/configparser.py", line 379, in before_set "position %d" % (value, tmp_value.find('%'))) ValueError: invalid interpolation syntax in 'postgresql://coreapi:***@bayesian-pgbouncer:5432/coreapi?sslmode=disable' at position 26 + current= + popd + '[' -z f8bb0efac483 ']' ~ The DB version should be f8bb0efac483, but is . Maybe DB migration is still in progress/failed? + '[' f8bb0efac483 '!=' '' ']' + echo 'The DB version should be f8bb0efac483, but is . Maybe DB migration is still in progress/failed?' + exit 1 
```

**Comment by msrb** [comment]
This is likely regression caused by recent code refactoring around configuration.

**Comment by msrb** [comment]
This should be fixed already, thanks @pkajaba 😉 Closing...
