### ISSUE TITLE
duplicate key value violates unique constraint "pg_type_typname_nsp_index"

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-worker#570]
On starting an ingestion for new package:

http://localhost:32000/api/v1/component-analyses/maven/org.apache.tomcat:tomcat-servlet-api/8.5.6

Following error is observed

```
worker-ingestion_1      | 2018-03-14 07:19:37,892 [WARNING] celery.backends.database: Failed operation _store_result.  Retrying 2 more times.
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-ingestion_1      |     cursor.execute(statement, parameters)
worker-ingestion_1      | psycopg2.IntegrityError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
worker-ingestion_1      | DETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.
worker-ingestion_1      | 
worker-ingestion_1      | 
worker-ingestion_1      | The above exception was the direct cause of the following exception:
worker-ingestion_1      | 
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 53, in _inner
worker-ingestion_1      |     return fun(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 105, in _store_result
worker-ingestion_1      |     session = self.ResultSession()
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 99, in ResultSession
worker-ingestion_1      |     **self.engine_options)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 59, in session_factory
worker-ingestion_1      |     self.prepare_models(engine)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 54, in prepare_models
worker-ingestion_1      |     ResultModelBase.metadata.create_all(engine)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
worker-ingestion_1      |     tables=tables)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
worker-ingestion_1      |     conn._run_visitor(visitorcallable, element, **kwargs)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
worker-ingestion_1      |     **kwargs).traverse_single(element)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-ingestion_1      |     return meth(obj, **kw)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
worker-ingestion_1      |     _is_metadata_operation=True)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-ingestion_1      |     return meth(obj, **kw)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
worker-ingestion_1      |     include_foreign_key_constraints=include_foreign_key_constraints
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
worker-ingestion_1      |     return meth(self, multiparams, params)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
worker-ingestion_1      |     return connection._execute_ddl(self, multiparams, params)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
worker-ingestion_1      |     compiled
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
worker-ingestion_1      |     exc_info
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker-ingestion_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
worker-ingestion_1      |     raise value.with_traceback(tb)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-ingestion_1      |     cursor.execute(statement, parameters)
worker-ingestion_1      | sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
worker-ingestion_1      | DETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.
worker-ingestion_1      |  [SQL: '\nCREATE TABLE celery_tasksetmeta (\n\tid INTEGER NOT NULL, \n\ttaskset_id VARCHAR(155), \n\tresult BYTEA, \n\tdate_done TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id), \n\tUNIQUE (taskset_id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/gkpj)

```

**Comment by tuxdna** [comment]
I see this exception again on my local setup.

**Comment by tuxdna** [comment]
```
worker-api_1            | 2018-03-14 11:55:06,023 [WARNING] celery.backends.database: Failed operation _store_result.  Retrying 2 more times.
worker-api_1            | Traceback (most recent call last):
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-api_1            |     context)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-api_1            |     cursor.execute(statement, parameters)
worker-api_1            | psycopg2.IntegrityError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
worker-api_1            | DETAIL:  Key (typname, typnamespace)=(celery_taskmeta, 2200) already exists.
worker-api_1            | 
worker-api_1            | 
worker-api_1            | The above exception was the direct cause of the following exception:
worker-api_1            | 
worker-api_1            | Traceback (most recent call last):
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 53, in _inner
worker-api_1            |     return fun(*args, **kwargs)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 105, in _store_result
worker-api_1            |     session = self.ResultSession()
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 99, in ResultSession
worker-api_1            |     **self.engine_options)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 59, in session_factory
worker-api_1            |     self.prepare_models(engine)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 54, in prepare_models
worker-api_1            |     ResultModelBase.metadata.create_all(engine)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
worker-api_1            |     tables=tables)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
worker-api_1            |     conn._run_visitor(visitorcallable, element, **kwargs)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
worker-api_1            |     **kwargs).traverse_single(element)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-api_1            |     return meth(obj, **kw)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
worker-api_1            |     _is_metadata_operation=True)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-api_1            |     return meth(obj, **kw)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
worker-api_1            |     include_foreign_key_constraints=include_foreign_key_constraints
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
worker-api_1            |     return meth(self, multiparams, params)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
worker-api_1            |     return connection._execute_ddl(self, multiparams, params)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
worker-api_1            |     compiled
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
worker-api_1            |     context)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
worker-api_1            |     exc_info
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker-api_1            |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
worker-api_1            |     raise value.with_traceback(tb)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-api_1            |     context)
worker-api_1            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-api_1            |     cursor.execute(statement, parameters)
worker-api_1            | sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
worker-api_1            | DETAIL:  Key (typname, typnamespace)=(celery_taskmeta, 2200) already exists.
worker-api_1            |  [SQL: '\nCREATE TABLE celery_taskmeta (\n\tid INTEGER NOT NULL, \n\ttask_id VARCHAR(155), \n\tstatus VARCHAR(50), \n\tresult BYTEA, \n\tdate_done TIMESTAMP WITHOUT TIME ZONE, \n\ttraceback TEXT, \n\tPRIMARY KEY (id), \n\tUNIQUE (task_id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/gkpj)
coreapi-pgbouncer       | 2018-03-14 11:55:06.061 13 LOG C-0xe8c448: coreapi/coreapi@172.17.0.12:39978 login attempt: db=coreapi user=coreapi tls=no
worker-ingestion_1      | 2018-03-14 11:55:06,032 [WARNING] celery.backends.database: Failed operation _store_result.  Retrying 2 more times.
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-ingestion_1      |     cursor.execute(statement, parameters)
worker-ingestion_1      | psycopg2.ProgrammingError: relation "celery_tasksetmeta" already exists
worker-ingestion_1      | 
worker-ingestion_1      | 
worker-ingestion_1      | The above exception was the direct cause of the following exception:
worker-ingestion_1      | 
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 53, in _inner
worker-ingestion_1      |     return fun(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 105, in _store_result
worker-ingestion_1      |     session = self.ResultSession()
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 99, in ResultSession
worker-ingestion_1      |     **self.engine_options)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 59, in session_factory
worker-ingestion_1      |     self.prepare_models(engine)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 54, in prepare_models
worker-ingestion_1      |     ResultModelBase.metadata.create_all(engine)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
worker-ingestion_1      |     tables=tables)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
worker-ingestion_1      |     conn._run_visitor(visitorcallable, element, **kwargs)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
worker-ingestion_1      |     **kwargs).traverse_single(element)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-ingestion_1      |     return meth(obj, **kw)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
worker-ingestion_1      |     _is_metadata_operation=True)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-ingestion_1      |     return meth(obj, **kw)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
worker-ingestion_1      |     include_foreign_key_constraints=include_foreign_key_constraints
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
worker-ingestion_1      |     return meth(self, multiparams, params)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
worker-ingestion_1      |     return connection._execute_ddl(self, multiparams, params)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
worker-ingestion_1      |     compiled
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
worker-ingestion_1      |     exc_info
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker-ingestion_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
worker-ingestion_1      |     raise value.with_traceback(tb)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-ingestion_1      |     cursor.execute(statement, parameters)
worker-ingestion_1      | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "celery_tasksetmeta" already exists
worker-ingestion_1      |  [SQL: '\nCREATE TABLE celery_tasksetmeta (\n\tid INTEGER NOT NULL, \n\ttaskset_id VARCHAR(155), \n\tresult BYTEA, \n\tdate_done TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id), \n\tUNIQUE (taskset_id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)

```

**Comment by msrb** [comment]
I've never seen this error before. Please make sure you start with clean environment (`./docker-compose.sh down -v` and with latest changes (`./docker-compose.sh build --no-cache`).

**Comment by tuxdna** [comment]
With latest images and code I get this error again:


```
worker-ingestion_1      | 2018-03-14 19:30:51,709 [INFO] celery.worker.strategy: Received task: selinon.Dispatcher[42b06626-dff9-4cda-8302-5753342975e8]  
worker-ingestion_1      | 2018-03-14 19:30:51,711 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f2a9388a378> (args:('selinon.Dispatcher', '42b06626-dff9-4cda-8302-5753342975e8', {'argsrepr': '()', 'kwargsrepr': "{'flow_name': 'bayesianFlow', 'node_args': {'force': False, 'name': 'org.apache.tomcat:tomcat-servlet-api', 'force_graph_sync': True, 'version': '8.5.6', 'ecosystem': 'maven'}}", 'correlation_id': '42b06626-dff9-4cda-8302-5753342975e8', 'id': '42b06626-dff9-4cda-8302-5753342975e8', 'delivery_info': {'routing_key': 'tuxdna_ingestion_bayesianFlow_v0', 'priority': None, 'redelivered': False, 'exchange': ''}, 'root_id': '42b06626-dff9-4cda-8302-5753342975e8', 'lang': 'py', 'task': 'selinon.Dispatcher', 'group': None, 'origin': 'gen96@55513b1bb580', 'expires': None, 'parent_id': None, 'eta': None, 'retries': 0, 'reply_to': '083b16e0-e5ce-3a6d-bc55-a42ad434f93e', 'timelimit': [None, None]}, '[[], {"flow_name": "bayesianFlow", "node_args": {"force": false, "name": "org.apache.tomcat:tomcat-servlet-api", "force_graph_sync": true, "version": "8.5.6", "ecosystem": "maven"}}, {"errbacks": null, "chord": null, "chain": null,... kwargs:{})
worker-ingestion_1      | 2018-03-14 19:30:51,716 [DEBUG] celery.worker.request: Task accepted: selinon.Dispatcher[42b06626-dff9-4cda-8302-5753342975e8] pid:1
coreapi-pgbouncer       | 2018-03-14 19:30:51.757 14 LOG C-0x1a52448: coreapi/coreapi@172.18.0.14:50204 login attempt: db=coreapi user=coreapi tls=no
coreapi-pgbouncer       | 2018-03-14 19:30:51.766 14 LOG S-0x1a57280: coreapi/coreapi@172.18.0.4:5432 new connection to server (from 172.18.0.8:37194)
coreapi-pgbouncer       | 2018-03-14 19:30:51.842 14 LOG C-0x1a522c0: coreapi/coreapi@172.18.0.12:41160 closing because: client close request (age=0)
coreapi-pgbouncer       | 2018-03-14 19:30:51.857 14 LOG C-0x1a52448: coreapi/coreapi@172.18.0.14:50204 closing because: client close request (age=0)
worker-ingestion_1      | 2018-03-14 19:30:51,855 [WARNING] celery.backends.database: Failed operation _store_result.  Retrying 2 more times.
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-ingestion_1      |     cursor.execute(statement, parameters)
worker-ingestion_1      | psycopg2.ProgrammingError: relation "celery_taskmeta" already exists
worker-ingestion_1      | 
worker-ingestion_1      | 
worker-ingestion_1      | The above exception was the direct cause of the following exception:
worker-ingestion_1      | 
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 53, in _inner
worker-ingestion_1      |     return fun(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 105, in _store_result
worker-ingestion_1      |     session = self.ResultSession()
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/__init__.py", line 99, in ResultSession
worker-ingestion_1      |     **self.engine_options)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 59, in session_factory
worker-ingestion_1      |     self.prepare_models(engine)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/backends/database/session.py", line 54, in prepare_models
worker-ingestion_1      |     ResultModelBase.metadata.create_all(engine)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
worker-ingestion_1      |     tables=tables)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
worker-ingestion_1      |     conn._run_visitor(visitorcallable, element, **kwargs)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
worker-ingestion_1      |     **kwargs).traverse_single(element)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-ingestion_1      |     return meth(obj, **kw)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
worker-ingestion_1      |     _is_metadata_operation=True)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker-ingestion_1      |     return meth(obj, **kw)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
worker-ingestion_1      |     include_foreign_key_constraints=include_foreign_key_constraints
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
worker-ingestion_1      |     return meth(self, multiparams, params)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
worker-ingestion_1      |     return connection._execute_ddl(self, multiparams, params)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
worker-ingestion_1      |     compiled
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
worker-ingestion_1      |     exc_info
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker-ingestion_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
worker-ingestion_1      |     raise value.with_traceback(tb)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker-ingestion_1      |     context)
worker-ingestion_1      |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker-ingestion_1      |     cursor.execute(statement, parameters)
worker-ingestion_1      | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "celery_taskmeta" already exists
worker-ingestion_1      |  [SQL: '\nCREATE TABLE celery_taskmeta (\n\tid INTEGER NOT NULL, \n\ttask_id VARCHAR(155), \n\tstatus VARCHAR(50), \n\tresult BYTEA, \n\tdate_done TIMESTAMP WITHOUT TIME ZONE, \n\ttraceback TEXT, \n\tPRIMARY KEY (id), \n\tUNIQUE (task_id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)

```

**Comment by jpopelka** [comment]
I tried with pulled images, but haven't seen it.

**Comment by msrb** [comment]
@tuxdna is it possible that you have some celery+sentry configuration leftovers on your system?

**Comment by tuxdna** [comment]
Other's are not seeing same issue. Holding this back as this seems like a false alarm on my system.
